### ISSUE TITLE
No English language strings available for translation in AMOS

### ISSUE THREAD

**Issue by germanvaleroelizondo** [EduardoKrausME/moodle-local-kopere_dashboard#1]
Hi,

I wanted to translate into Spanish your local_kopere plugin, but it is not hosted in AMOS at https://lang.moodle.org/ .

This is usually caused by a coding error.

Can you please have a look at the developer's documentation at https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings ?

Thanks in advance

**Comment by eduardokraus** [comment]
Sí, seguí este manual.

He abierto una ISSUE para Moodle.org comprobar.

**Comment by germanvaleroelizondo** [comment]
Gracias Eduardo.

Ya descubrí la causa de que no aprezcan las cadenas en AMOS :(

Tu plugin está clasificado como "En incubación", alojado en https://moodle.org/plugins/browse.php?list=category&id=60 

Los plugins en incubación NO exportan sus cadenas de idioma a AMOS.

Mucho me temo que solamente podrá haber progreso cuando logres que te transfieran el plugin a la categoría de local normal.

Mientras tanto ¿querrías/podrías añadir los paquetes de las traducciones es y es_mx adentro de la carpeta lang del plugin aquí en GitHub, para que formen parte del ZIP descargable  y les funcione a los hispanohablantes?

O, si lo prefieres, yo las traduzco del inglés y te las mando. 

GRACIAS.
