### ISSUE TITLE
Performance test results with disabled guest login

### ISSUE THREAD

**Issue by ElectricCircus** [EduardoKrausME/moodle-local-kopere_dashboard#100]
Testing version 2.6.25 of the plugin in Moodle 4.4.4+:

The performance test reports excessive delay for a site where guest login has been disabled.
The plugin should detect this condition and perhaps ignore or not compute the check for the "Time to connect with the guest account" item.

I'm not sure how it should proceed with the "fake user account login", because I guess that must end in a timeout if the site is rejecting fake user logins, as indeed.

Thanks!

![image](https://github.com/user-attachments/assets/d76a3e5a-5a7e-4f2f-8af8-ca927b9eff4a)

**Comment by eduardokraus** [comment]
Hello,  

I would like to clarify how the plugin handles "guest account login" and "fake account login" during performance testing:  

1. **Guest Login**:  
   When guest login is disabled, the plugin temporarily enables this option solely for the test. After performing the login and completing the necessary checks, it disables the functionality again. This process is designed to be quick and secure, ensuring that the original state of the site is restored immediately after the test.  

2. **Fake Account Login**:  
   During this test, the plugin creates a temporary (fake) user account in the system. Once created, the login is performed to assess performance. As soon as the test is completed, the account is automatically deleted. This method ensures that no fake accounts remain in the system after the procedure.
