### ISSUE TITLE
Missing language string for cache definition

### ISSUE THREAD

**Issue by volodymyrdovhan** [EduardoKrausME/moodle-local-kopere_dashboard#103]
Hello,
I found a missing language string for the cache definition.
Please add the cache name to the lang file:

![image](https://github.com/user-attachments/assets/acdc1fe3-cedc-4085-a5ce-917c43ef1908)

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/baebffbf736e3999623ec0c722bd81927442e11f
