### ISSUE TITLE
Another hard-wired portuguese language string (Integracoes)

### ISSUE THREAD

**Issue by germanvaleroelizondo** [EduardoKrausME/moodle-local-kopere_dashboard#11]
Hi Eduardo.

When testing the new 1.3.5 version (which looks very nice), I came across another portuguese language string that looks like 'Integrações', which I think is 'Integrations':

![kopere integrations](https://user-images.githubusercontent.com/2671923/34505755-d112f8da-efec-11e7-9bb8-3b88a8155c8f.png)

Feliz año nuevo :)

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/ea99d49beac4c8364c4962910e21f6eb95d04b27
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/ddf9aaee49bfae29ff6d1a99cf3869fdab89f434
