### ISSUE TITLE
Reports page are hard-wired in Spanish

### ISSUE THREAD

**Issue by germanvaleroelizondo** [EduardoKrausME/moodle-local-kopere_dashboard#12]
While testing version 1.3.5, I noticed that the Reports page displays all  the strings in Mexican Spanish, even though the site language were selected to English or Brazilian Portuguese:

![kopere reports en](https://user-images.githubusercontent.com/2671923/34506400-f41a0fc6-eff1-11e7-9fa7-59a544bd6676.png)
![kopere reports pt_br](https://user-images.githubusercontent.com/2671923/34506404-f81fe398-eff1-11e7-81c9-5acdd74be1e9.png)

**Comment by germanvaleroelizondo** [comment]
Version 1.3.6 still has this issue :(

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/04ab4b47540272b311b208e23116426cbffb9935
