### ISSUE TITLE
Conflict between Policies and Kopere plugins causes error for Managers trying to access Site Administration

### ISSUE THREAD

**Issue by bollycanuk** [EduardoKrausME/moodle-local-kopere_dashboard#16]
I'm running into issues with a possible conflict between the Kopere Dashboard plugin and the Policies plugin (https://moodle.org/plugins/tool_policy).

If I set the Policy handler to Policies (tool_policy) in Site administration/Privacy and policies/Policy settings and Kopere is installed, I get the following error if I login as a Manager and try to access Site Administration. If I uninstall the Kopere plugin there is no error, Similarly if I uninstall the Policies plugin and reinstall the Kopere plugin there is no error

Exception - Call to a member function add() on null

More information about this error

**×Debug info:** 
Error code: generalexceptionmessage
**×Stack trace:**
line 55 of /local/kopere_dashboard/settings.php: Error thrown
line 67 of /lib/classes/plugininfo/local.php: call to include()
line 642 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
line 8000 of /lib/adminlib.php: call to require()
line 26 of /admin/search.php: call to admin_get_root()

I'm running Moodle 3.4.2 on a Linux VPS with PHP 7.0.30 and MySQL 5.6.38. The problem also occurs with the latest 3.4.2+

cheers,
Derek

**Comment by eduardokraus** [comment]
Got corrected. Take a test
