### ISSUE TITLE
This  plugin does not implement Moodle Privacy API

### ISSUE THREAD

**Issue by germanvaleroelizondo** [EduardoKrausME/moodle-local-kopere_dashboard#17]
Este plugin no implementa la API de privacidad de Moodle. Si este plugin almacena algunos datos personales, no podrán ser exportados o eliminados mediante el sistema de privacidad de Moodle.

Please see https://docs.moodle.org/35/en/View_plugin_privacy_registry

And https://docs.moodle.org/dev/Privacy_API

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/b88e1c3d21bb24d402dfcf5e43f1c155f45ec0fd
