### ISSUE TITLE
Large number displayed has wrong thousands separator

### ISSUE THREAD

**Issue by germanvaleroelizondo** [EduardoKrausME/moodle-local-kopere_dashboard#2]
![screen shot 2017-11-23 at 19 58 38](https://user-images.githubusercontent.com/2671923/33192520-d26057e2-d088-11e7-955c-366583e89b11.png)
While trying the local kopere dashboard, the number shown in the Users/Assets red coloured box for my University (Moodle 3.2) server is shown as 12.692 / 8.483

But in my country (Mexico) the thousands separator is a comma not a point.
This point as a thousands separator would be OK for Spain, but it is wrong for many Moodle sites that use a decimal separator (most of the word).

The number shown here should use the thousands separator defined by the language pack as seen in https://docs.moodle.org/dev/Translation_langconfig#thousandssep.2Ccore_langconfig

Thanks in advance for your help.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/e8f518773fd27b63b2c652db299a1f93cb8a3392

**Comment by germanvaleroelizondo** [comment]
Thanks a lot Eduardo :)
