### ISSUE TITLE
Adicionar novos campos na exportação de todos os cursistas

### ISSUE THREAD

**Issue by Data-Sora** [EduardoKrausME/moodle-local-kopere_dashboard#21]
Seria interessante poder adicionar outros campos na exportação de todos os cursistas do moodle
Relatórios -> Relatórios de Usuários -> Todos os usuários

**Comment by JersainGzz** [comment]
Hubo alguna respuesta en referencia a si se pueden abrir nuevos campos? y porque a mi no me aparecen los usuarios en linea

**Comment by eduardokraus** [comment]
Estou fazendo editor de relatórios
