### ISSUE TITLE
Información Erronea

### ISSUE THREAD

**Issue by JersainGzz** [EduardoKrausME/moodle-local-kopere_dashboard#22]
Hola como puedo ajustar la información arrojada ya que me muestra en el tablero que tengo ocupado que hay 712.6 GB ocupados de los cuales el reporte detallado me arroja una vez haciendo la suma de 320 GB 

Moodle 3.5.4
MySQL 5.5.60
PHP 7.1.17

**Comment by eduardokraus** [comment]
El complemento agrega lo que hay en la base de datos.
