### ISSUE TITLE
Tags are not replaced

### ISSUE THREAD

**Issue by hebertpxx** [EduardoKrausME/moodle-local-kopere_dashboard#24]
I received a email about a submit, but the configurated tags were not replaced. See attach file.
![plugin-kopere](https://user-images.githubusercontent.com/33330466/54530363-52b8aa00-4961-11e9-9ada-d17912fa6be3.PNG)

**Comment by malinskyt** [comment]
Hi there,
i have the same problem. Tags is not replaced. 
What can be a problem?
Thx TM
