### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by hebertpxx** [EduardoKrausME/moodle-local-kopere_dashboard#25]
When you try to add a notification, the screen dims and the "New Notification" box is shown below, but it does not respond to clicks. I had to use the Browser Inspect to can add a new notification.

![box](https://user-images.githubusercontent.com/33330466/54530734-57ca2900-4962-11e9-9bf0-b527abd030a3.PNG)

**Comment by eduardokraus** [comment]
Solved
