### ISSUE TITLE
Exception - Call to a member function add() on null

### ISSUE THREAD

**Issue by michael-milette** [EduardoKrausME/moodle-local-kopere_dashboard#27]
The following exception happens on one of our user's computers, but not on others, when she goes to the **Site Administration** page:

**Exception - Call to a member function add() on null**

**Debug info:**

Error code: generalexceptionmessage

**Stack trace:**

* Line 56 of /local/kopere_dashboard/settings.php: Error thrown
* line 67 of /lib/classes/plugininfo/local.php: call to include()
* line 642 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
* line 8065 of /lib/adminlib.php: call to require()
* line 26 of /admin/search.php: call to admin_get_root()

**Output buffer:**

Notice: Undefined variable: settings in /local/kopere_dashboard/settings.php on line 56

**Additional information:**

* Moodle 3.6.3+ (Build: 20190406)
* Kopere Dashboard 2019040800
* Theme: Boost and others.
* User role: Administrator

**Comment by michael-milette** [comment]
Just wanted to add some information. Turns out that this seems to affect all of our Moodle Managers (site-wide).

To work around the problem, all I did was just deactivate the plugin and, without even having to log out and back in again, all of the Moodle Managers can now access the Site Administration menu once again.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/43f39221235abee45db356da64f145d7616b2c63

**Comment by rpardog** [comment]
Hi I have the following moodle setup:

- moodle version 4.2.1+ (Build: 20230714)
- mariadb database 11.1.1
- php version 8.0.28

I have installed the Kopere Dashboard Plugin

- Kopere Dashboard 2.5.22
- local_kopere_dashboard 2023071200

And I get the following error:

`_Excepción - method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

[Más información sobre este error](https://docs.moodle.org/402/es/error/moodle/generalexceptionmessage)

Información de depuración:
Error code: generalexceptionmessage×Descartar esta notificación
Trazado de la pila (stack):
line 49 of /local/kopere_dashboard/settings.php: TypeError thrown
line 49 of /local/kopere_dashboard/settings.php: call to method_exists()
line 67 of /lib/classes/plugininfo/local.php: call to include()
line 810 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
line 8760 of /lib/adminlib.php: call to require()
line 31 of /admin/search.php: call to admin_get_root()
×Descartar esta notificación
Buffer de salida: <br /> <b>Warning</b>: Undefined variable $settings in <b>/var/www/html/campus/local/kopere_dashboard/settings.php</b> on line <b>49</b><br />_`

I cannot access the Site Administration with the Manager user.

How can I solve that
