### ISSUE TITLE
Notificação sobre Novos Alunos para Professores

### ISSUE THREAD

**Issue by desenvolvefacil** [EduardoKrausME/moodle-local-kopere_dashboard#33]
Não é disparado o email para os professores quando há matricula de um novo aluno.

**Comment by eduardokraus** [comment]
Você configurou o SMTP?

https://moodle.eduardokraus.com/como-receber-uma-notificacao-toda-ves-que-um-aluno-se-auto-inscrever-no-moodle

**Comment by desenvolvefacil** [comment]
EduardoKrausME/moodle-local-kopere_dashboard,



O seu email para nosso sistema de suporte não pode ser aceito porque não foi reconhecido como vinda de um endereço de e-mail pertencente a um dos nossos clientes. Se precisar de ajuda, por favor, envie um e-mail a partir do endereço que você registrou conosco e que você usa para acessar a nossa área de cliente.

Servidor Fácil - Desenvolve Fácil - Sistemas em Internet e Hospedagem

*Este é um email disparado automaticamente pelo sistema, caso precise de suporte abra um Ticket em:

http://www.financeiro.servidorfacil.com.br/submitticket.php
