### ISSUE TITLE
More feature request then real Issue

### ISSUE THREAD

**Issue by Brada65** [EduardoKrausME/moodle-local-kopere_dashboard#35]
I following your work on dashboard closely from beginning mid 2017, and I have only best things to say about it.
But recently have mishap, and unfortunately deleted only version of your dashboard that have backup option in it (first version).
I agree that shouldn't be an option on live (production site), but it is very practical to have it for local instances (in my case on WAMP) as replacement for snapshot of the server (quick backup of just that one instance of moodle).
Can you introduce again backup as optional, for example to have option in settings (where "open in popup" is ) where administrator can choose if wants to show (use) "Backup" on menu of "Kopere Dashboard". If that is not possible, can you please send me the first version (if you have it) of "Kopere Dashboard" plugin.

**Comment by eduardokraus** [comment]
Moodle.org asked to remove the resource.
