### ISSUE TITLE
Issue/Sugestion Large website optimizations

### ISSUE THREAD

**Issue by jonnyso** [EduardoKrausME/moodle-local-kopere_dashboard#36]
I'm trying to use the plugin on a very large website, both database and moodledata. I'm constantly having timeout errors because the queries the plugin runs on start are taking too long. Is there a way to optmize it ? I noticed that there is no configuration other than how it should be shown (pop up, embed, etc).

**Comment by ElectricCircus** [comment]
Hi buddy!

Have you tried increasing the timeout parameters on PHP?

**Comment by ElectricCircus** [comment]
> I'm trying to use the plugin on a very large website, both database and moodledata. I'm constantly having timeout errors because the queries the plugin runs on start are taking too long. Is there a way to optmize it ? I noticed that there is no configuration other than how it should be shown (pop up, embed, etc).

Hi buddy!

Have you tried increasing the timeout parameters on PHP?

**Comment by eduardokraus** [comment]
I am testing some improvements. Especially in reports

**Comment by jonnyso** [comment]
Thank you @eduardokraus . @ElectricCircus , I could do that but larger execution times can lead to certain vulnerabilities.
