### ISSUE TITLE
Export to Excel error

### ISSUE THREAD

**Issue by ElectricCircus** [EduardoKrausME/moodle-local-kopere_dashboard#38]
Hi!

I´m running Kopere v2.4.3 with Moodle 3.8.2+ Build 20200312: when pressing the Export to Excel button on Reports returns a "404 Not found page".

The URL is "https://www.eduneu.com.ar/isicollege/plataforma/local/kopere_dashboard/classname=reports&method=load_report&type=course&report=5&courseid=2&export=xls"

Thanks.
![Captura Kopere Excel 1](https://user-images.githubusercontent.com/40699731/77162522-e815df00-6a8a-11ea-8df9-7e717cc208c1.JPG)
![Captura Kopere Excel 2](https://user-images.githubusercontent.com/40699731/77162529-eba96600-6a8a-11ea-87f0-c7a91e376d97.JPG)

**Comment by eduardokraus** [comment]
Sorted out. Wait for commit

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/77a963b8c91ebdf3f338f36ea580dce9ee231fb1
