### ISSUE TITLE
BREAKS SITE - HTTP 500 on upgrade from 2020062001 to 2020062003

### ISSUE THREAD

**Issue by demontech** [EduardoKrausME/moodle-local-kopere_dashboard#39]
I have a version of M3.4 and upgrading to your latest version and I can't upgrade once I hit to upgrade it breaks the site 

HTTP ERROR 500

Please help

Thanks

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/499baeda25405cdf065c99e3d1dbe370df66db02

**Comment by demontech** [comment]
STILL ERRORS 

![image](https://user-images.githubusercontent.com/8148238/77276812-c0846980-6c78-11ea-85d7-f06531c13f70.png)

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/80e7230bbf2d7bf4e95f51df4127bf5bd3bed02e
