### ISSUE TITLE
Hard-wired English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [EduardoKrausME/moodle-local-kopere_dashboard#4]
Hi,
I have made a local customization of the all the English language strings in your plugin, BUT
There aree some English language strings that have not been available for translation, as they are not string variables, but are hard-wired constants.
I think your plugin would be even better if it were possible to translate all of this English language strings.
I have enclosed some screen images to illustrate the strings:
![kopere hardwired 03](https://user-images.githubusercontent.com/2671923/33225381-f3f10074-d13b-11e7-8965-11e57555297c.png)
![kopere hardwired 02](https://user-images.githubusercontent.com/2671923/33225382-f403cb78-d13b-11e7-8c22-8526d2537640.png)
![kopere hardwired 01](https://user-images.githubusercontent.com/2671923/33225383-f4179a04-d13b-11e7-9002-2f11232d93af.png)

Thanks in advance.

**Comment by germanvaleroelizondo** [comment]
Most strings are now translated :)

BUT the disk usage report has a button with portuguese language text that is not available for language customization/translation. See enclosed image:
![kopere disk usage report](https://user-images.githubusercontent.com/2671923/33889982-76799fa4-df17-11e7-8694-15b4740a6712.png)

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/366c9fb2d1c539907877f57b68c7cf4179bc95bb
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/366c9fb2d1c539907877f57b68c7cf4179bc95bb
