### ISSUE TITLE
Does not display dashboard

### ISSUE THREAD

**Issue by demontech** [EduardoKrausME/moodle-local-kopere_dashboard#40]
version 2020062004

![image](https://user-images.githubusercontent.com/8148238/77277411-11e12880-6c7a-11ea-9118-c8f63d9b2789.png)

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/80e7230bbf2d7bf4e95f51df4127bf5bd3bed02e
