### ISSUE TITLE
Incompatibilidade Javascriot

### ISSUE THREAD

**Issue by victeo** [EduardoKrausME/moodle-local-kopere_dashboard#42]
Olá! Já adianto que estou amando seu plugin, porém, na versão mais recente do tema moove, está tendo uma incompatibilidade com o javascritp, não deixando abrir nenhuma das abas. 
Vc tem alguma sugestão para resolver? 
Abraços!

**Comment by mathiasribeiro** [comment]
Também uso este tema tá com esse bug.
