### ISSUE TITLE
maneira de abrir o painel "Kopere"

### ISSUE THREAD

**Issue by luisrobertoflores** [EduardoKrausME/moodle-local-kopere_dashboard#48]
como posso mudar a maneira de abrir o painel "Kopere"? Selecionei "pop-up", mas agora queria mudar para "abrir por dentro". Você poderia me dizer o procedimento? ou devo ter que reinstalá-lo?

**Comment by eduardokraus** [comment]
Em configurações >> Plugins >> Plugins locais >> Kopere Dashboard
