### ISSUE TITLE
Mexican Spanish translated language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [EduardoKrausME/moodle-local-kopere_dashboard#5]
Hi,
While your plugin is in the incubating-experimental category, the English language strings can not be translated in AMOS.

I enclose a full translation for the es_mx language pack of the existing strings.

You can add them to the lang folder of the plugin as es_mx. You can also add an exact copy as es (International Spanish).

Thanks in advance.

[es.zip](https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/files/1502678/es.zip)

**Comment by eduardokraus** [comment]
Muchas gracias

Añada créditos a usted

https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/76f918d2f748d995ff00775daccdffa05226ad31

**Comment by germanvaleroelizondo** [comment]
Hi Eduardo,

Can you please copy all the lang/es folder contents into a nw lang/es_mx  folder ?

**Comment by germanvaleroelizondo** [comment]
Thanks Eduardo.
