### ISSUE TITLE
When download the data in Course report/Courses that have groups enabled page, the value of column Group Mode is empty

### ISSUE THREAD

**Issue by johnpap21** [EduardoKrausME/moodle-local-kopere_dashboard#57]
Course   report/Courses that have groups enabled
Check   the downloaded excel content

![image](https://user-images.githubusercontent.com/32021311/87062694-4ebf3400-c205-11ea-8962-bc1076b73a20.png)

**Comment by eduardokraus** [comment]
Solved this problem
