### ISSUE TITLE
"Erro: Ajax error" dialog is displayed when continuous switched page/updated results per page in Student count in each course report page.

### ISSUE THREAD

**Issue by johnpap21** [EduardoKrausME/moodle-local-kopere_dashboard#58]
User   Report/Student count in each course

Check   the display 10/25/50/100 results per page
Click   the previous and next

![image](https://user-images.githubusercontent.com/32021311/87062843-7f06d280-c205-11ea-9281-bf09b10ce437.png)

**Comment by eduardokraus** [comment]
Solved this problem
