### ISSUE TITLE
Erro: Requested unknown parameter '0' for row 0, column 0

### ISSUE THREAD

**Issue by MarcioMartyria** [EduardoKrausME/moodle-local-kopere_dashboard#59]
IN:
/local/kopere_dashboard/open-internal.php?classname=pay-transacoes&method=dashboard&course=###

Os resultados das transações (PagSeguro) não são exibidos, embora clicando na linha (em branco) apareça a transação.
![image](https://user-images.githubusercontent.com/68127234/87192295-8fce4b80-c2cc-11ea-9232-54311de3fa55.png)
![image](https://user-images.githubusercontent.com/68127234/87192315-9c52a400-c2cc-11ea-8d56-df291e694f87.png)

**Comment by eduardokraus** [comment]
Solved this problem
