### ISSUE TITLE
Cadastro de Cupons 

### ISSUE THREAD

**Issue by profaristoteles** [EduardoKrausME/moodle-local-kopere_dashboard#62]
Módulo de Pagamentos não consigo gerar cupons, sempre aparece esta mensagem...
Cupom deve possuir 100% caracteres!

**Comment by eduardokraus** [comment]
Isso porque em Configurações, em Tamanho dos cupons você escreveu "100%" ao invés e um número. 

Existe uma descrição abaixo falando que deve add número.

**Comment by profaristoteles** [comment]
Troquei por número e tem essa informação "Deixe em branco que o Sistema gera automaticamente", deixo em branco e o sistema informa " Cupom deve possuir 8 caracteres! "

**Comment by eduardokraus** [comment]
Acesse https://centraldocliente.eduardokraus.com/ e atualize o Kopere Pay

**Comment by profaristoteles** [comment]
a versão que tem é 6.0.8 e já estou usando ela

**Comment by eduardokraus** [comment]
Add 6.0.9

**Comment by profaristoteles** [comment]
Obg agora deu certo
