### ISSUE TITLE
Páginas Estáticas - Não visivel 

### ISSUE THREAD

**Issue by profaristoteles** [EduardoKrausME/moodle-local-kopere_dashboard#64]
Estou com o Dashboard atualizado e as Páginas Estáticas criadas não ficam visível. Faço edição e nada.

**Comment by lsolla** [comment]
Usando o Kopere Dashboard, criei um menu e, em seguida, uma página associada a ele.
Eu indiquei que queria a página visível e me mostrou o indicador "visível" igual a 1, mas ao salvar, "visível" volta a 0.
Tentei editar a página e mudar "visível" para 1, mas ao salvar, "visível" continua voltando para 0.
Acho que essa é a razão pela qual a página criada não está aparecendo no menu de navegação.
Como posso tornar a página visível no menu de navegação?

**Comment by eticialima** [comment]
@eduardokraus Estou com problema quando crio paginas estatica. Consigo cricar o menu mas quando eu crio a pagina e salvo aparece essa mensagem abaixo. O que pode ser ? 
![image](https://user-images.githubusercontent.com/58613583/172861529-c6d041a6-eba5-4f92-a5b2-79923ff0fff4.png)
