### ISSUE TITLE
Páginas de gerenciamento de  matrículas manuais no Moodle inacessíveis

### ISSUE THREAD

**Issue by conexaomedica** [EduardoKrausME/moodle-local-kopere_dashboard#71]
Ao instalar O KoperePay as páginas de gerenciamento de  matrículas manuais no Moodle ( /enrol/users.php?id=iddocurso)  são redirecionas e não é mais possível inscrever usuários manualmente nos cursos.

Precisa ser revertido ou haver haver esta opção em outro lugar

**Comment by eduardokraus** [comment]
Vai em Administração do site >> Plugins >> Plugins Locais >> Kopere Pay desative a opção de redirecionar da página enrol

**Comment by conexaomedica** [comment]
Olá,

Não existe Administração do site >> Plugins >> Plugins Locais >> Kopere Pay
Será que o Plugin precisa de uma atualização?
Dashboard de Pagamento 2020091000

![KoperePay](https://user-images.githubusercontent.com/5614550/123846671-0d2f0980-d8ec-11eb-8256-cabbbaee640c.jpg)
