### ISSUE TITLE
In the dashboard view hamburger button stops working

### ISSUE THREAD

**Issue by mattgig** [EduardoKrausME/moodle-local-kopere_dashboard#75]
As soon as you install the Kopere Dashboard in Moodle 3.11.1 the Hamburger button stops working. It doesn't react when you press the hamburger button and you can't close the side menu. On other pages it still works.

Steps to reproduce:
1. Install plugin
2. Go to dashboard
3. Press hamburger button

In the browser console you get an error:

require.min.js:5 Uncaught Error: Mismatched anonymous define() module: function(){"use strict";var t;function l(){return t.apply(null,arguments)}function e(e){t=e}function r(e){return e instanceof Array||Object.prototype.toString.call(e)==="[object Array]"}function s(e){return e instanceof Date||Object.prototype.toString.call(e)==="[object Date]"}function n(e,t){var n=[],i;for(i=0;i<e.length;++i){n.push(t(e[i],i))}return n}function o(e,t){return Object.prototype.hasOwnProperty.call(e,t)}function a(e,t){for(var n in t){if(o(t,n)){e[n]=t[n]}}if(o(t,"toString")){e.toString=t.toString}if(o(t,"valueOf")){e.valueOf=t.valueOf}return e}function f(e,t,n,i){return Ht(e,t,n,i,true).utc()}function i(){return{empty:false,unusedTokens:[],unusedInput: ...

I wonder whether you can replicate that issue or if it is an unfortunate interaction with other plugins.

**Comment by michbalazs** [comment]
I had the same issue and the user menu didnt work

**Comment by eduardokraus** [comment]
test now
