### ISSUE TITLE
Erro de codificação

### ISSUE THREAD

**Issue by GiulianoMachado** [EduardoKrausME/moodle-local-kopere_dashboard#78]
Nos relatorios do kopere, na opção de login de usuarios ele gera um relatorio desde o inicio e na opção de edição de relatorio não tem como incluir periodo ou outra opção de pesquisa, tem opção para separar por curso, mas quando tentei mudar ele deu erro. Erro de codificação detectado e deve ser corrigido por um programador: **moodle_database::update_record_raw() id field must be specified**

**Comment by eduardokraus** [comment]
Resolvido
