### ISSUE TITLE
I Can't save a report

### ISSUE THREAD

**Issue by diermava** [EduardoKrausME/moodle-local-kopere_dashboard#79]
Hello,

I have a problem when exporting a report to excel because the generated url does not precede the open-internal.php? and it generates an error.

Could you help me to know how should I modify my open-internal.php file to make it work?

I send you an error about how you are generating the url when you click on the Export to excel button:

mysite/moodle/local/kopere_dashboard/classname=reports&method=load_report&type=course&report=5&courseid=4&export=xls

And the correct url should be

mysite/moodle/local/kopere_dashboard/open-internal.php?classname=reports&method=load_report&type=course&report=5&courseid=4&export=xls

**Comment by eduardokraus** [comment]
Resolvido
