### ISSUE TITLE
 error with moodle version 3.11.5+

### ISSUE THREAD

**Issue by fbbraga** [EduardoKrausME/moodle-local-kopere_dashboard#82]
Friends, my kopere is not working after installing moodle 3.115+. It opens the window for the dashboard but does not show the data
![2](https://user-images.githubusercontent.com/71727582/152353635-07c47680-b99d-4037-b508-fb9c50b30a1e.PNG)
![Capturar](https://user-images.githubusercontent.com/71727582/152353639-d4184ca2-46c2-450e-a2d4-c1cc758b45d3.PNG)

**Comment by eduardokraus** [comment]
Resolvido
