### ISSUE TITLE
Cadastrar usuário

### ISSUE THREAD

**Issue by vivianevs** [EduardoKrausME/moodle-local-kopere_dashboard#84]
Olá, 
na descrição do plugin informa que posso importar usuários dentro do moodle pelo kopere,, não achei como fazer isso, poderia me ajudar?

**Comment by eduardokraus** [comment]
![Captura de Tela 2024-09-01 às 13 54 53](https://github.com/user-attachments/assets/eee3baaa-9508-484c-92e5-e435fc197858)
