### ISSUE TITLE
Kopere Pay não está inscrevendo alunos no curso

### ISSUE THREAD

**Issue by kellyrdias** [EduardoKrausME/moodle-local-kopere_dashboard#85]
Não sei o que preciso fazer, mas o Kopere Pay DashBoard não está inscrevendo os alunos automaticamente nos cursos do moodle.
Os alunos se autenticam, pagam pelo curso, mas quando são direcionados para o painel não aparece o curso pra eles e tenho que fazer a inscrição de forma manual.

No teste de desempenho aparece isso:

Exceção - Class 'local_kopere_dashboard\performancemonitor' not found

[Outras informações sobre este erro](https://docs.moodle.org/400/pt_br/error/moodle/generalexceptionmessage)
![image](https://user-images.githubusercontent.com/86796011/206314944-456b0eeb-4ac9-437e-b0b3-d9a9e84eb92b.png)

**Comment by eduardokraus** [comment]
Atualize o Kopere
