### ISSUE TITLE
Replace hard-wired portuguese language strings with English language variables

### ISSUE THREAD

**Issue by germanvaleroelizondo** [EduardoKrausME/moodle-local-kopere_dashboard#9]
Hi, 

Using Notepad++  'Search in files' I found a few ocurrences of the portuguese word 'dados' in your plugin. While most of them were (obviously) in the lang/pt_br folder, two were not:

  F:\M\M340\server\moodle\local\kopere_dashboard\classes\performancemonitor.php (1 hit)
	Line 221:         echo '<br/>Dados: ';
  F:\M\M340\server\moodle\local\kopere_dashboard\classes\reports.php (1 hit)
	Line 182:                 button::primary('Baixar estes dados', "reports::download&report={$report}&courseid={$courseid}");
 
I will try to learn how to make this change in my GitHub fork of your plugin and I will later do a pull request (if I finally learn how to do it ).

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-local-kopere_dashboard/commit/4581863a3b9d3eb62970ed040c13b1ab9e5b43b0
