### ISSUE TITLE
Erro ao criar novo relatório

### ISSUE THREAD

**Issue by matstauder** [EduardoKrausME/moodle-local-kopere_dashboard#90]
Olá, Eduardo, tudo bem?

Estou utilizando o seu plugin kopere dashboard em um ambiente moodle meu e estou com um problema, não estou conseguindo adicionar novos relatórios. Sempre que adiciono novos reports ele me informa  o erro "tabela "report" não existe". Como consigo criar novos reports sem encontrar este erro? pode me orientar?

**Comment by eduardokraus** [comment]
Este erro ja foi corrigido a um bom tempo

**Comment by eduardokraus** [comment]
Resolvido
