### ISSUE TITLE
The latest update is not being installed

### ISSUE THREAD

**Issue by prabodhcp** [EduardoKrausME/moodle-local-kopere_dashboard#91]
HI there is a problem with the recent update. I have Moodle 4.2.2 running Kopere Dashboard 2.5.22 2023071200. I see that there is a new update 2023072900 but if I install the update it installs the older version (2023071200) itself. And again it keeps prompting that there is a newer version available.

The same issue occurred when i uninstalled the plugin and reinstalled it.

**Comment by germanhgarcia** [comment]
I have version Moodle 4.2.2, when I install version 2023072900 Kopere doesn't work I get an error that says division by zero and Kopere doesn't run. Does anyone know how I can install Kopere Dashboard in version 4.2.2?

**Comment by atassano** [comment]
I have Moodle 4.14 in dev and a local for testing level 1 with 4.01. In both cases I have downloaded 2023072900, but It installs 2023071200.

I'm using Debian 11.3. In both cases, Moodle notifiy me that there is an update available (2023072900), but reinstalls previous version.

**Comment by eduardokraus** [comment]
I submitted an update to fix this.

**Comment by atassano** [comment]
Thank you Eduardo!!
