### ISSUE TITLE
Error with cron local_kopere_dashboard\task\db_course_access

### ISSUE THREAD

**Issue by mciotti** [EduardoKrausME/moodle-local-kopere_dashboard#93]
Hi,
I got this error in db postgres during the scheduled task's run : 
ERROR:  column "mdl_logstore_standard_log.timecreated" must appear in the GROUP BY clause or be used in an aggregate function
LINE 3: ...             courseid, userid, contextinstanceid, timecreate...

I think it's enought add the field in the group by clause...

Here the complete log:
Execute scheduled task: Cron to store user logins in temporary table (local_kopere_dashboard\task\db_course_access)
... started 16:48:04. Current memory use 5.7 MB.
... used 2 dbqueries
... used 0.0085229873657227 seconds
Scheduled task failed: Cron to store user logins in temporary table (local_kopere_dashboard\task\db_course_access),Si è verificato un errore durante la lettura del database (ERROR:  column "mdl_logstore_standard_log.timecreated" must appear in the GROUP BY clause or be used in an aggregate function
LINE 3: ...             courseid, userid, contextinstanceid, timecreate...
                                                             ^

                SELECT CONCAT(courseid,userid,contextinstanceid) AS a, COUNT(*) AS contagem,
                       courseid, userid, contextinstanceid, timecreated
                  FROM mdl_logstore_standard_log
                 WHERE action = 'viewed'
              GROUP BY courseid, userid, contextinstanceid
              ORDER BY timecreated DESC
[array (
)])
Debug info:
ERROR:  column "mdl_logstore_standard_log.timecreated" must appear in the GROUP BY clause or be used in an aggregate function
LINE 3: ...             courseid, userid, contextinstanceid, timecreate...
                                                             ^

                SELECT CONCAT(courseid,userid,contextinstanceid) AS a, COUNT(*) AS contagem,
                       courseid, userid, contextinstanceid, timecreated
                  FROM mdl_logstore_standard_log
                 WHERE action = 'viewed'
              GROUP BY courseid, userid, contextinstanceid
              ORDER BY timecreated DESC
[array (
)]
Backtrace:
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 358 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
* line 1044 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
* line 59 of /local/kopere_dashboard/classes/task/db_course_access.php: call to pgsql_native_moodle_database->get_records_sql()
* line 410 of /lib/classes/cron.php: call to local_kopere_dashboard\task\db_course_access->execute()
* line 208 of /lib/classes/cron.php: call to core\cron::run_inner_scheduled_task()
* line 125 of /lib/classes/cron.php: call to core\cron::run_scheduled_tasks()
* line 186 of /admin/cli/cron.php: call to core\cron::run_main_process()

Thanks in advance

**Comment by eduardokraus** [comment]
Ciao mciotti,

Grazie mille per aver condiviso il problema dell'errore SQL! Abbiamo identificato che la causa dell'errore era dovuta a una SQL errata per PostgreSQL. Abbiamo apportato le correzioni necessarie e ti chiediamo di effettuare un nuovo test per verificare se ora tutto funziona correttamente.

Se riscontri ancora qualche problema o hai altre domande, non esitare a segnalarcelo. Siamo qui per aiutarti!
