### ISSUE TITLE
Falha em tarefa do cron e não inscrição dos alunos na plataforma após a efetivação da compra e status "Concluído"

### ISSUE THREAD

**Issue by NicolasAlvesRibeiro** [EduardoKrausME/moodle-local-kopere_dashboard#97]
Olá @eduardokraus, tudo certo?

Após fazer a integração do plugin no Moodle com a loja (WooCommerce), fiz alguns testes de compra e mesmo com o status "concluído" o usuário que compra não esta sendo inscrito na plataforma. Verifiquei dentro do plugin e me aparece assim:

![Screenshot_1](https://github.com/user-attachments/assets/437d032f-0b2c-4c94-b504-e990109c1354)

Verifiquei também o cron e percebi que uma das tarefas não está sendo rodada:
![Screenshot_2](https://github.com/user-attachments/assets/b458ce2e-909e-4b03-a4fd-849b1ec21da9)

Creio que a tarefa que não esta sendo rodada pode estar ocasionando este problema, não tenho certeza. Vendo os logs da tarefa, joguei o erro no ChatGPT e ele me retornou o seguinte:

"O erro que você está encontrando na tarefa cron relacionada ao plugin Kopere Dashboard no Moodle está ligado a uma falha na consulta SQL. A parte que causa o problema é esta: 

CONCAT(courseid::text, userid::text, contextinstanceid::text)

A sintaxe ::text que está sendo usada para converter os valores de courseid, userid e contextinstanceid para texto é típica de bancos de dados como PostgreSQL, mas não é válida no MariaDB/MySQL, que é o banco de dados mais comum em servidores Moodle.

Para corrigir o erro, você pode alterar o código SQL, removendo o ::text e utilizando uma sintaxe compatível com o MariaDB, como:

CONCAT(courseid, userid, contextinstanceid)

O caminho ideal é revisar o arquivo db_course_access.php no plugin Kopere Dashboard e fazer as modificações necessárias na consulta SQL, adaptando a sintaxe para o banco de dados que você está utilizando (provavelmente MariaDB, no seu caso)."

@eduardokraus poderia me dar uma ajuda nisso, gostaria de ver o que você acha antes de modificar qualquer coisa nos arquivos do plugin.

Obrigado, aguardo retorno.

**Comment by eduardokraus** [comment]
O WooCommerce foi atualizado agora de manhã e a CRON foi atualizado ontem no #96
