### ISSUE TITLE
No aparecen los cursos.

### ISSUE THREAD

**Issue by oearenas** [EduardoKrausME/moodle-local-kopere_dashboard#98]
Hola!!!

Soy usuario de Moodle [4.0.12 (Build: 20231211)] 
Tengo instalada la ultima versión de su tablero

no me aparece la información de los cursos
no me aparece el progreso de los usuarios

agradecería su ayuda :) 

![image](https://github.com/user-attachments/assets/1eddeca2-1bd8-4cbc-ab45-7e241b2b8adc)
![image](https://github.com/user-attachments/assets/41ca2732-fdfb-4928-9966-44b9d93a78f1)

Gracias!!!

**Comment by eduardokraus** [comment]
¿Tienes la última versión de Kopere?

https://moodle.org/plugins/local_kopere_dashboard/2.6.15/33096

**Comment by oearenas** [comment]
La estoy instalando, revisaré si el problema se mantiene
![image](https://github.com/user-attachments/assets/503c3089-84db-42ae-ad67-69f0d42605cd)

**Comment by oearenas** [comment]
![image](https://github.com/user-attachments/assets/62c04b30-7b88-43c9-8ec4-f20cb6500c9d)

Sigue sin funcionar.
